### ISSUE TITLE
Does it work with Angular 6?

### ISSUE THREAD

**Issue by sem1colon** [surveyjs/surveyjs_angular_cli#39]
SurveyJS library works only with Angular 7+?
I'm getting type errors for knockout. Is there a supported version for Angular 6?
![image](https://user-images.githubusercontent.com/26898798/81166997-16f00200-8fb2-11ea-8352-64101a7f885a.png)

**Comment by tsv2013** [comment]
`survey-angular` library works with Angular 2+

**Comment by tsv2013** [comment]
Original discussion is here - https://surveyjs.answerdesk.io/ticket/details/t3976/how-to-fix-knockout-type-errors-for-angular-6

**Comment by sem1colon** [comment]
That doesn't solve. Any other solution?

**Comment by tsv2013** [comment]
@sem1colon You are asking the same question in two places - here and on our portal - https://surveyjs.answerdesk.io/ticket/details/t3976/how-to-fix-knockout-type-errors-for-angular-6

In what place do you prefere to discuss the question?

**Comment by sem1colon** [comment]
Lol, I thought that two different guys replying to me. Sorry about that.
I'm happy to discuss here because GitHub will have more reach & it will be useful to someone in the future.
By the way, Did you check my [project](https://github.com/sem1colon/SurveyJS-demo-angular6)?

**Comment by tsv2013** [comment]
Sure. I'll look into it and write here.

**Comment by tsv2013** [comment]
I've checked your project. I've made it work via:
removing the
```
    "survey-knockout": "^1.7.4",
```
and adding the 
```
    "@types/knockout": "^3.4.67",
```
in the `package.json` file.

But this is bad indeed, We have other corresponding issue in our answerdesk - https://surveyjs.answerdesk.io/ticket/details/t3116/trying-to-determine-which-version-of-survey-angular-and-associated-libraries-to-use-with

I've moved this task up in our task queue

**Comment by sem1colon** [comment]
@tsv2013 Thanks for the workaround.
Hope, it will be fixed in the future release.
And, I must appreciate for your quick responses to the inquiry.

**Comment by tsv2013** [comment]
I've fixed the issue via the [https://github.com/surveyjs/survey-library/commit/95d6e5c14e95f73505fc5e5d104646bcdb4c4af4][0] commit.
Now `survey.angular.d.ts` file doesn't reference knockoutjs library. Fix will be available in the 1.7.6 update most likely next tuesday. Could you check it on your side?

[0]: https://github.com/surveyjs/survey-library/commit/95d6e5c14e95f73505fc5e5d104646bcdb4c4af4

**Comment by sem1colon** [comment]
@tsv2013 I've installed both **survey-angular** & **survey-knockout** to the latest (v1.7.5) and checked, still, the type errors are coming.

**Comment by sem1colon** [comment]
@tsv2013 I am still getting the same type errors.
FYI, I installed both **survey-angular** & **survey-knockout** to the latest version(1.7.5) and installed `@types/knockout` as well.
However, when I checked this on [stackblitz](https://stackblitz.com/github/sem1colon/SurveyJS-demo-angular6), no type errors are coming. But when I tried local, I was getting errors.

**Comment by tsv2013** [comment]
@sem1colon If you are using the `survey-angular` library without survey-creator, you needn't to install neither `survey-knockout` nor `@types/knockout` types lbraries. Is it your case?

Your local project can lock reference versions in the `package-lock.json` file. Could you remove this file, remove the `node_modules` folder, reinstall packages via `npm i` and try again?
